name: recipeapptest
description: "A Flutter Recipe Application with BLoC and SQLite"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  sqflite: ^2.3.3+1
  path: ^1.9.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.1.1
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.1.2
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recipetypes.json
